include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat these as warnings so they don't block CI initially
    prefer_const_constructors: warning
    avoid_print: warning
    always_declare_return_types: warning
    prefer_single_quotes: info
    unawaited_futures: warning

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    always_declare_return_types: true
    prefer_single_quotes: true
    unawaited_futures: true
    cancel_subscriptions: true
